name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-pypi:
    name: Release (PyPI)
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Install PDM
        uses: pdm-project/setup-pdm@b2472ca4258a9ea3aee813980a0100a2261a42fc # v4.2
      - name: Build Distribution(s)
        run: pdm build --no-sdist
      - name: Publish Distribution(s)
        run: pdm publish --no-build
